"""Core data models for the Homebook generator."""

from dataclasses import dataclass, field
from fractions import Fraction
from typing import Optional, List, Dict, Any
from enum import Enum


class Difficulty(Enum):
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"
    MIXED = "mixed"


@dataclass
class WordProblemContext:
    """Context for a word problem generated by LLM."""
    story: str  # The story setup, e.g., "Emma ate 1/3 of a pizza..."
    question: str  # The question to solve, e.g., "How much did they eat together?"
    context_type: str  # The theme: cooking, sports, shopping, crafts, nature, school


@dataclass
class WordProblemConfig:
    """Configuration for word problem generation."""
    enabled: bool = False
    context_type: str = "mixed"  # cooking, sports, shopping, crafts, nature, school, mixed
    word_problem_ratio: float = 0.3  # 30% word problems by default


# Denominator pools by difficulty
DIFFICULTY_DENOMINATORS = {
    Difficulty.EASY: [2, 3, 4, 5, 6],
    Difficulty.MEDIUM: [2, 3, 4, 5, 6, 8, 10],
    Difficulty.HARD: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
}


@dataclass
class Problem:
    """Base problem class."""
    id: str
    question_text: str
    question_html: str
    answer: Any
    answer_text: str
    hint: Optional[str] = None
    worked_solution: Optional[str] = None
    visual_svg: Optional[str] = None
    topic: str = ""
    subtopic: str = ""
    difficulty: Difficulty = Difficulty.MEDIUM
    metadata: Dict[str, Any] = field(default_factory=dict)
    is_word_problem: bool = False
    word_problem_context: Optional[WordProblemContext] = None
    standards: List[str] = field(default_factory=list)  # List of standard codes (e.g., ["5.NF.A.1"])


@dataclass
class FractionProblem(Problem):
    """Fraction-specific problem with LCD/GCF info."""
    lcd: Optional[int] = None
    gcf: Optional[int] = None
    equivalent_fractions: Optional[Dict[str, str]] = None


@dataclass
class GeneratorConfig:
    """Configuration for worksheet generation."""
    topic: str
    subtopic: str
    num_problems: int = 10
    difficulty: Difficulty = Difficulty.MEDIUM

    # Options
    include_hints: bool = False
    include_worked_examples: bool = False
    include_visuals: bool = True
    include_answer_key: bool = True
    show_lcd_reference: bool = False
    include_intro_page: bool = False  # AI-generated intro page

    # Word problem options
    word_problem_config: Optional[WordProblemConfig] = None

    # Constraints
    max_denominator: int = 12
    allow_improper: bool = False
    require_simplification: bool = True

    # Personalization
    student_name: Optional[str] = None
    worksheet_title: Optional[str] = None
    teacher_name: Optional[str] = None
    date: Optional[str] = None
    grade_level: int = 5


@dataclass
class Worksheet:
    """Generated worksheet."""
    id: str
    config: GeneratorConfig
    problems: List[Problem]
    html_content: str
    pdf_url: Optional[str] = None
    created_at: Optional[str] = None
    standards: List[str] = field(default_factory=list)  # List of standard codes covered
    standards_display: str = ""  # Formatted for printing (e.g., "5.NF.A.1, 5.NF.A.2")
